### PR TITLE
Update for Cabal >= 2.2 and `base` >= 4.11

### LINKED ISSUE #2: Setup.hs does not compile with Cabal > 2.0.1.1
Problem: 

> /home/user/Packages/Haskell/Own/teilfeil-0.1.0.2/dist-newstyle/tmp/src-16404/blazeT-0.0.5/dist/setup/setup.hs:11:9:                           
> error:                                                                                                                                        
> Not in scope: ‘haddockHscolour’                                                                                                               
> Perhaps you meant ‘haddockHscolourCss’ (imported from                                                                                         
> Distribution.Simple.Setup)                                                                                                                    
> )                      
> 

Reason: package Cabal:
Distribution.Simple.Setup.HaddockFlags
does not anymore have the field:
haddockHscolour.

Solution:

Remove corresponding line in Setup.hs

### PR DESCRIPTION
**Pull request by habibalamin**
This fixes #2, which is `Setup.hs` not working for Cabal > 2.0.1.1, and an issue without a ticket, which is `base` >= 4.11 breaking the Monoid instance.

I have not tested anything except compilation with Cabal 3.10.1.0 and `base` 4.17.2.0 (GHC 9.4.7). It should also work on `base` 4.18/GHC 9.6, and I've tried to maintain backward-compatibility with older Cabal/GHC/`base` versions, too.

While I didn't test compilation with older versions, my HLS seemed to be smart enough to pick up on the CPP macros and warn me about, e.g. `mappend` being `(<>)` (or vice versa, I forget) only on the older version when I copy-pasted a small piece of code. That same chunk of code didn't have the warning on the #ifdef pertaining to the version I had installed. That was pretty cool.

### CODE REVIEW

**Comment by habibalamin** [comment]
See discussion in #1 for why I've now closed this.
